### ISSUE TITLE
Add TryFrom implementation

### ISSUE THREAD

**Issue by Stargateur** [Kestrer/bounded-integer#4]
Why not ?

**Comment by Stargateur** [comment]
Maybe not a good idea, this would prevent user to implement From

**Comment by Kestrer** [comment]
Wait, would it? I do actually want to implement this if it's possible.

**Comment by Stargateur** [comment]
I'm not sure, https://doc.rust-lang.org/std/convert/trait.TryFrom.html:

```rust
impl<T, U> TryFrom<U> for T where
    U: Into<T>, 
```

This blanket implement `TryFrom` if type implement `From` (cause `From` also have blanket implement) that make sense but I'm not sure that if you implement `TryFrom` this would result in a conflict implementation if the user of bounded-integer want to implement a From in case the type have default.

- need to check this
- guess you will decide what to do after
