### ISSUE TITLE
Clappy warning manual_range_contains

### ISSUE THREAD

**Issue by Stargateur** [Kestrer/bounded-integer#5]
the proc macro generate a clappy warning https://rust-lang.github.io/rust-clippy/master/index.html#manual_range_contains

https://github.com/Kestrer/bounded-integer/blob/89d5a187f98d0cd042ffbe35658af2dd0643df78/macro/src/generate.rs#L188

I don't have strong opinion about this warning but this break my workflow :p

**Comment by Kestrer** [comment]
Fixed in 0.4.0.
