### ISSUE TITLE
RANGE break thing

### ISSUE THREAD

**Issue by Stargateur** [Kestrer/bounded-integer#7]
`RANGE` is implemented using `repr` this cause problem cause for signed number this can lead to overflow for example:

```rust
bounded_integer::bounded_integer! {
    #[repr(i32)]
    pub struct TimeOut { -1..2147483647 }
}
```

https://github.com/Kestrer/bounded-integer/blob/3997eaa4ae56f74bd1f62b1699d8ab1b59259647/macro/src/generate.rs#L138

that generate `ì32::MAX + 1 + 1` that of course will overflow.

Bound like `0..u32:MAX` will also overflow I think at this rate `RANGE` should just be remove or transform to a function that return `Option<T>`.

**Comment by Kestrer** [comment]
I've removed `RANGE` and `new_wrapping` (which relied on `RANGE`, and had other problems with overflow) in 0.4.0.
